on:
  issues:
    types: [opened, edited]

jobs:
  auto_close_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Automatically close issues that don't follow the issue template
        uses: Bluethefurry/auto-close-issues@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}